config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :posts
    resources :categories
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts do
    resources :messages, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  get '/index' => 'posts#index_all', :as => "index_all"
  resources :users, only: [:show]
  get '/info' => 'users#info', :as => "user_infos"
  get '/historys' => 'users#history', :as => "historys"
  root 'posts#index'
  resources :auctions
  get '/sub_cate' => 'auctions#sub_cate', :as => "sub_cate"
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  after_create :assign_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :rememberable, :trackable, :validatable,
    :omniauthable, :omniauth_providers => [:facebook]
  has_many :messages
  has_many :posts
  has_many :favorites, inverse_of: :user
  has_many :auctions
  # has_many :posts, :foreign_key => :favoritable_id, :class_name => 'Favorite', :source => 'Post', :condition => ['favoritable_type=Post']
  belongs_to :school, inverse_of: :users
  validates_numericality_of :school_id, :only_integer => true
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.school_id = 1
    end
  end
  def assign_default_role
    add_role(:member) if self.roles.blank?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	layout 'user'
  before_action :authenticate_user!

  def info
  end
  
  def show
  	@favorites = current_user.favorites.includes(:favoritable)
  end

  def history
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/history.html.erb
<div class="container">
  <h3>歷史紀錄</h3>
  <table class="table table-hover table-responsive">
    <tr class="table-row">
      <td>#</td>
      <td>PostName</td>
      <td><span class="glyphicon glyphicon-comment" aria-hidden="true"></span></td>
      <td><span class="glyphicon glyphicon-heart" aria-hidden="true"></span></td>
      <td><span class="glyphicon glyphicon-trash" aria-hidden="true"></td>
    </tr>
    <% current_user.posts.each_with_index do |f, idx| %>
      <tr>
        <td><%= (idx+1) %></td>
        <td><%= link_to f.name, post_path(f) %></td>
        <td><%= f.messages.count %></td>
        <td><%= f.favorites.count %></td>
        <td><%= link_to "Delete", post_path(f), method: :delete, class: 'btn btn-warning', data: { confirm: 'are you sure?'} %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/info.html.erb
<div class="container">
	<div class="row">
		<div class="info-pic"></div>
		<div class="left-info">
		  <h3>發文數: <%= link_to current_user.posts.count, historys_path %></h3>
		</div>
		<div class="left-info">
		  <h3>喜歡數: <%= link_to current_user.favorites.count, user_path(current_user) %></h3>
	  </div>
	  <h4><%= current_user.name %></h4>
	  <h4><%= current_user.email %></h4>
	  <h3><%= current_user.roles[0].name %></h3>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h3>喜歡的文章</h3>
  <table class="table table-hover">
    <tr>
      <td>#</td>
      <td>Title</td>
    </tr>
    <% @favorites.order('favoritable_type, favoritable_id').each_with_index do |t, idx| %>
      <tr>
        <td><%= (idx+1) %></td>
        <td><%= link_to t.favoritable[:name], t.favoritable %></td>
      </tr>
    <% end %>
  </table>
</div>