config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :posts
    resources :categories
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts do
    resources :messages, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  get '/index' => 'posts#index_all', :as => "index_all"
  resources :users, only: [:show]
  get '/info' => 'users#info', :as => "user_infos"
  get '/historys' => 'users#history', :as => "historys"
  root 'posts#index'
  resources :auctions
  get '/sub_cate' => 'auctions#sub_cate', :as => "sub_cate"
end

app/models/admin/post.rb
class Admin::Post < Post
	resourcify
end

app/models/post.rb
require 'uri'
class Post < ActiveRecord::Base
  resourcify
  include Bootsy::Container
  acts_as_punchable
  has_many :favorites, :as => :favoritable
  has_many :messages, :inverse_of => :post
  belongs_to :user
  belongs_to :type, :inverse_of => :posts
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  def self.sample_cover_img(post)
    cover = URI.extract(post.content, ['http','https'])
    post.cover_image = cover.sample
  end

  def self.like_or_not?(user, post)
    user.favorites.posts.pluck(:favoritable_id).include?(post.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  layout 'admin'
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  def index
    @admin_posts = Admin::Post.all
  end

  # GET /admin/posts/1
  def show
  # question
    @post = Post.find(params[:id])
    @messages = Message.where(post_id: @admin_post)
  end

  # GET /admin/posts/new
  def new
    @admin_post = Admin::Post.new
  end
  # POST /admin/posts
  def create
    @admin_post = Admin::Post.new(admin_post_params)
    if @admin_post.save
      redirect_to @admin_post
      flash[:notice] = 'Post was successfully created.'
    else
      render :new
    end
  end

  # GET /admin/posts/1/edit
  def edit
  end


  # PATCH/PUT /admin/posts/1
  def update
      if @admin_post.update(admin_post_params)
        redirect_to @admin_post
        flash[:notice] = 'Post was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /admin/posts/1
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_post_params
      params.require(:admin_post).permit(:name, :content, :avatar)
    end
end

app/controllers/posts_controller.rb
require 'uri'
class PostsController < ApplicationController
  layout 'post'
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :index_all, :show]
  def index
    @posts = Post.all
  end

  def index_all
    @posts = Post.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @post_favorite =  current_user.favorites.find_by(:favoritable_id => @post.id) if user_signed_in?
    @favorite_id = @post_favorite[:id] unless @post_favorite.nil?
    @post.punch(request)
    @messages = Message.where(post_id: @post).includes(:user)
    render :layout => 'show_post'
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    Post.sample_cover_img(@post) if !@post.avatar_file_name?
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    Post.sample_cover_img(@post) if !@post.avatar_file_name?
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :avatar)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/post_helper.rb
module PostHelper
	 # ***************
	 #     首頁圖片
	 # ***************
  def index_cover_image(post)
    if post.avatar_file_name?
      link_to (image_tag post.avatar.url(:medium)), post,class: 'thumbnail'
    else
      link_to (image_tag post.cover_image), post, class: 'thumbnail'
    end
  end
  # ***************
	#  	 show_page
  # ***************
  def have_avatar_file
  	image_tag @post.avatar.url(:medium) if @post.avatar_file_name?
  end

  def have_favorites_id_or_not
  	if user_signed_in?
  		if @post.favorites.pluck(:user_id).include?(current_user.id)
  			favorite_id = @post.favorites.find_by(:user_id => current_user.id).id
  		end
  	end
    p "_________________FFFFFF____IIIIDDDD____#{favorite_id}"
  	return favorite_id
  end
end

app/views/admin/posts/_form.html.erb
<%= simple_form_for(@admin_post) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, label: 'Post Title', :input_html => {class: 'form-control'} %>
  <%= f.input :content, as: :bootsy%>
  <%= f.button :submit, class: 'btn btn-default' %>
  <%= link_to "Cancel", :back, class: 'btn btn-default' %>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Admin Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_post %> |
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Posts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_posts.each do |admin_post| %>
      <tr>
        <td><%= admin_post.name %></td>
        <td><%= link_to 'Show', admin_post %></td>
        <td><%= link_to 'Edit', edit_admin_post_path(admin_post) %></td>
        <td><%= link_to 'Destroy', admin_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_admin_post_path %>

app/views/admin/posts/new.html.erb
<h1>New Admin Post</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="text">
	<%= image_tag @post.avatar.url(:medium) if @post.avatar_file_name? %>
	<h1><%= @post.name %></h1>
	<h5>Post by <%= @post.user.name %></h5>
	<h3><%= simple_format(@post.content) %></h3>
</div>
<%= link_to 'Edit', edit_admin_post_path(@admin_post), class: 'btn btn-default' %>
<%= link_to 'Back', admin_posts_path, class: 'btn btn-default' %>
<hr>