config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :posts
    resources :categories
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts do
    resources :messages, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  get '/index' => 'posts#index_all', :as => "index_all"
  resources :users, only: [:show]
  get '/info' => 'users#info', :as => "user_infos"
  get '/historys' => 'users#history', :as => "historys"
  root 'posts#index'
  resources :auctions
  get '/sub_cate' => 'auctions#sub_cate', :as => "sub_cate"
end

app/models/admin/category.rb
class Admin::Category < Category
  resourcify
end

app/models/category.rb
class Category < ActiveRecord::Base
  resourcify
  has_many :auctions
  validates_uniqueness_of :category_name
  scope :roots, -> {where("parent_id = -1")}
  # scope :sub_categories, -> (id) { where("parent_id = ?", id) }
  # 
  def self.sub_categories
    if sub = Category.where.not("parent_id = -1").pluck(:category_name, :id, :parent_id)
      return sub
    else
      return Category.all
    end
  end

  # def self.is_root?(category)
  #   return category.parent_id == -1
  # end

  # def self.roots
  #   return Category.where(:parent_id => -1)
  # end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
    before_action :find_admin_category, only: [:show, :edit, :update, :destroy]
  def index
    @admin_categories = Admin::Category.roots
    @admin_subcategories = Category.sub_categories
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
  end

  def new
    @admin_category = Admin::Category.new
  end

  def create
    @admin_category = Admin::Category.new(admin_category_params)
    if @admin_category.save
      redirect_to @admin_category
      flash[:notice] = 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
      if @admin_category.update(admin_category_params)
        redirect_to @admin_category
        flash[:notice] = 'Category was successfully updated.'
      else
        render :edit
    end
  end

  def destroy
    @admin_category.destroy
      redirect_to category_path 
  end

  def sub_cate  
   options = ""  
   @category = Category.where "parent_id =?", (params[:id])
   @category.each do |c|  
     options << "<option value=#{c.id}>#{c.category_name}</option>"  
   end
   # else
   #  @category = Category.where "parent_id =?", '7'
   #  @category.each do |c|  
   #    p c
   #  end
   # end  
   render :text => options  
 end

  private
    def find_admin_category
      @admin_category = Admin::Category.find(params[:id])
    end

    def admin_category_params
      params.require(:admin_category).permit(:category_name, :parent_id)
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/views/admin/categories/_category_list.html.erb
<%if @admin_subcategories%>
  <% @admin_subcategories.each do |category| %>
    <li pid="<%=category[2]%>">
      <h2><%= category[0] %></h2>
    </li>
  <% end %>
<%end%>

app/views/admin/categories/_form.html.erb
<div>
<%= simple_form_for @admin_category, html: {class: 'form-horizobtal', multipart: true } do |f| %>
    <%= f.input :category_name, :label => "類別" %>
    <%= f.collection_select(:parent_id, Admin::Category.roots, :id, :category_name, {:prompt => "請選擇"})%>
    <%= f.button :submit , :class => "btn btn-default"%>
    <%= link_to "Cancel", auctions_path, class: "btn btn-default" %>
<% end %>
</div>

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
<div>
  <select id="gg">
    <%@admin_categories.each do |c|%>
      <option value="<%=c.id%>"><%=c.category_name%></option>
    <%end%>
  </select>

  <script type="text/javascript">
    $(document).ready(function(){
      hideAllSubCategories();
      bindFirstTeirSelectChangeEvent();
      forceSelect();
    });

    function hideAllSubCategories(){
      $("li").hide();
    }

    function bindFirstTeirSelectChangeEvent(){
      $("#gg").change(function(){
        hideAllSubCategories();
        $("li[pid='"+$(this).val()+"']").show();
      });
    }

    function forceSelect(){
      $("#gg").trigger('change');
    }
    
  </script>


</div>
<div>
  <ul id="categories">
    <%= render 'category_list' %>
  </ul>     
</div>
  <%= link_to 'New', new_admin_category_path, class: 'btn btn-default' %>
</body>
</html>

app/views/admin/categories/new.html.erb
<h1>新增分類</h1>
<%= render 'form' %>

app/views/admin/categories/show.html.erb
<div class="row">
  <dd><%= @admin_category.category_name%></dd>
  <%= link_to "Back", admin_categories_path, class: "btn btn-default" %>
</div>