config/routes.rb
Rails.application.routes.draw do
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  namespace :admin do
    resources :posts
    resources :categories
  end
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  resources :posts do
    resources :messages, only: [:create]
    resources :favorites, only: [:create, :destroy]
  end
  get '/index' => 'posts#index_all', :as => "index_all"
  resources :users, only: [:show]
  get '/info' => 'users#info', :as => "user_infos"
  get '/historys' => 'users#history', :as => "historys"
  root 'posts#index'
  resources :auctions
  get '/sub_cate' => 'auctions#sub_cate', :as => "sub_cate"
end

app/models/admin/post.rb
class Admin::Post < Post
	resourcify
end

app/models/post.rb
require 'uri'
class Post < ActiveRecord::Base
  resourcify
  include Bootsy::Container
  acts_as_punchable
  has_many :favorites, :as => :favoritable
  has_many :messages, :inverse_of => :post
  belongs_to :user
  belongs_to :type, :inverse_of => :posts
  has_attached_file :avatar, styles: { medium: "300x300", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  def self.sample_cover_img(post)
    cover = URI.extract(post.content, ['http','https'])
    post.cover_image = cover.sample
  end

  def self.like_or_not?(user, post)
    user.favorites.posts.pluck(:favoritable_id).include?(post.id)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController
  layout 'admin'
  before_action :set_admin_post, only: [:show, :edit, :update, :destroy]

  # GET /admin/posts
  def index
    @admin_posts = Admin::Post.all
  end

  # GET /admin/posts/1
  def show
  # question
    @post = Post.find(params[:id])
    @messages = Message.where(post_id: @admin_post)
  end

  # GET /admin/posts/new
  def new
    @admin_post = Admin::Post.new
  end
  # POST /admin/posts
  def create
    @admin_post = Admin::Post.new(admin_post_params)
    if @admin_post.save
      redirect_to @admin_post
      flash[:notice] = 'Post was successfully created.'
    else
      render :new
    end
  end

  # GET /admin/posts/1/edit
  def edit
  end


  # PATCH/PUT /admin/posts/1
  def update
      if @admin_post.update(admin_post_params)
        redirect_to @admin_post
        flash[:notice] = 'Post was successfully updated.'
      else
        render :edit
      end
  end

  # DELETE /admin/posts/1
  def destroy
    @admin_post.destroy
    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: 'Post was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_post
      @admin_post = Admin::Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_post_params
      params.require(:admin_post).permit(:name, :content, :avatar)
    end
end

app/controllers/posts_controller.rb
require 'uri'
class PostsController < ApplicationController
  layout 'post'
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :index_all, :show]
  def index
    @posts = Post.all
  end

  def index_all
    @posts = Post.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @post_favorite =  current_user.favorites.find_by(:favoritable_id => @post.id) if user_signed_in?
    @favorite_id = @post_favorite[:id] unless @post_favorite.nil?
    @post.punch(request)
    @messages = Message.where(post_id: @post).includes(:user)
    render :layout => 'show_post'
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    Post.sample_cover_img(@post) if !@post.avatar_file_name?
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    Post.sample_cover_img(@post) if !@post.avatar_file_name?
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
    def find_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:name, :content, :avatar)
    end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/post_helper.rb
module PostHelper
	 # ***************
	 #     首頁圖片
	 # ***************
  def index_cover_image(post)
    if post.avatar_file_name?
      link_to (image_tag post.avatar.url(:medium)), post,class: 'thumbnail'
    else
      link_to (image_tag post.cover_image), post, class: 'thumbnail'
    end
  end
  # ***************
	#  	 show_page
  # ***************
  def have_avatar_file
  	image_tag @post.avatar.url(:medium) if @post.avatar_file_name?
  end

  def have_favorites_id_or_not
  	if user_signed_in?
  		if @post.favorites.pluck(:user_id).include?(current_user.id)
  			favorite_id = @post.favorites.find_by(:user_id => current_user.id).id
  		end
  	end
    p "_________________FFFFFF____IIIIDDDD____#{favorite_id}"
  	return favorite_id
  end
end

app/views/posts/_detail.html.erb
<h1><%= @post.name %></h1>
  <% if @post.user_id? %>
    <h5><%= @post.user.name %> | <%= @post.user.school.name unless @post.user.school_id.blank? %></h5>
    <h5>發佈於: <%= @post.created_at %></h5>
  <% else %>
    <h5>Post from <%= link_to "PTT",@post.ptt_post_link, target: '_blank' %></h5>
  <% end %>
<h3><%= simple_format(@post.content) %></h3>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :avatar, label: 'Cover Image', hint: '若無特定，隨機給圖。' %>
  <%= collection_select(:post, :type_id, Type.all, :id, :name) %>
  <%= f.input :name, label: 'Post Title', :input_html => {class: 'form-control'} %>
  <%= f.input :content, as: :bootsy%>
  <%= f.button :submit, class: 'btn btn-default' %>
  <%= link_to "Cancel", :back, class: 'btn btn-default' %>
<% end %>

app/views/posts/_like.html.erb
<% if user_signed_in? %>
    <button class="btn btn-default btn-success" id="favorited_button">Liked!</button>
    <button class="btn btn-default" id="favorites_button">Like</button>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to 'New', new_post_path, class: 'btn btn-default' %>
<div class="row posts">
  <div class="title">
    附近熱門
    <%= link_to "and more...", index_all_path, class: "more" %>
  </div>
  <% @posts.most_hit.each do |post| %>
  <div class="col-xs-6 col-md-2 box">
    <div class="image-wrapper overlay-fade-in" >
    <% if post.cover_image || post.avatar_file_name %>
      <%= index_cover_image(post) %>
    <% else %>
      <%= link_to (image_tag "default.jpg"), post, class: 'thumbnail'  %>
    <% end %>
        <div class="image-overlay-content" onclick='location.href="posts/<%=post.id%>"'>
        <h2><%= link_to post.name, post %></h2>
      </div>
      <div class="post_data">
        <i class="fa fa-eye"> <%= post.hits %></i>
        <i class="fa fa-heart"><%= post.favorites.count %></i>
      </div>
    </div>
  </div>
  <% end %>
</div>
<script type="text/javascript">
  $('.posts img').css('height','130px');
</script>

app/views/posts/index_all.html.erb
<%= link_to 'New', new_post_path, class: 'btn btn-default' %>
<div id="npage">
  <%= will_paginate @posts, :style=>"display:none;"%>
</div>
<div class="row posts"  id="masonry">
  <% @posts.order('id DESC').each do |post| %>
  <div class="col-xs-6 col-md-2 box">
    <div class="image-wrapper overlay-fade-in" >
    <% if post.cover_image || post.avatar_file_name %>
      <%= index_cover_image(post) %>
    <% else %>
      <%= image_tag "default.jpg", class: 'thumbnail'  %>
    <% end %>
      <div class="image-overlay-content fancybox" rel="gallery"  data-fancybox-href="posts/<%=post.id%>" href="javascript:;">
        <h2><%= post.name %></h2>
      </div>
      <div class="post_data">
        <i class="fa fa-eye"> <%= post.hits %></i>
        <i class="fa fa-heart"><%= post.favorites.count %></i>
      </div>
    </div>
  </div>
  <% end %>
</div>

<script type="text/javascript">
  $(function() {
    var $container = $('#masonry');
    $container.imagesLoaded(function(){
      $container.masonry({
        columnWidth: 20,
        itemSelector: '.box',
        gutter: 20
      });
    });
    $container.infinitescroll({
      navSelector : "#npage",
      nextSelector : "#npage a",
      itemSelector : ".box",
      pixelsFromNavToBottom: 300
    },
    function(newElements) {
      var $newElems = $(newElements).css({opacity: 0});
      $newElems.imagesLoaded(function(){
        $newElems.animate({opacity: 1});
        $container.masonry('appended', $newElems, true);
      });
    });
    $(".fancybox").fancybox({
      // API options 
      openEffect  : 'elastic',
      closeEffect : 'elastic',
      autoScale: false,
      type: 'iframe',
      padding: 0,
      autoSize: false,
      width: "55%",
      height: "auto",
      helpers : {
        overlay : {
          css : {
              'background' : 'rgba(0, 0, 0, .8)'
          }
        }
      }
    });
  });
</script>

app/views/posts/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<button id="alertB">Hi</button>
<article id="show-info" class="text">
  <%= render 'detail' %>
</article>
<hr>
<div class="text-info">
  <%= link_to "Home", root_path, class: "btn btn-default" %>
  <%= render 'like' %>
  <% if @post.user == current_user  %>
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-default" %>
    <%= link_to "Delete", post_path(@post), method: :delete, class: "btn btn-default" %>
  <% end %>
  <%= social_share_button_tag(@post.name, :popup => "true", :url => "http://127.0.0.1:3000/posts/#{@post.id}", :desc => "The best Search") %>
</div>
<h2><%= pluralize(@post.messages.count, "Reply")%></h2>
<% @messages.each do | message| %>
  <div class="message">
    <p class="username"><%= message.user.name %></p>
    <p class="time"><%= time_ago_in_words(message.created_at) %></p>
    <p class="msg"><%= message.msg %></p>
  </div>
<% end %>

<%= render 'messages/form' %>

<script type="text/javascript">
  $(document).ready(function() {
    var post_id     = <%= @post[:id] %>
    var favorite_id = <%= @favorite_id %>
    alertModule.initialize(post_id, favorite_id);
    alertModule.likeOrDislike();
  });
</script>